import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { useState } from 'react';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { parseID, verifyLink, getPlaylist } from './api/spotifyapi';

const inter = Inter({ subsets: ['latin'] })
const defaultArt = 'https://developer.spotify.com/images/guidelines/design/icon2@2x.png'

// This page handles the callback from Spotify's auth
// Users will select a playlist to rank

export default function Home() {
    const [currentAlbum, setCurrentAlbum] = useState(undefined);
    console.log(currentAlbum);

    function handleChangeLinks(e) {
      // If the link is valid, set it as the current album
      // and save the ID in local storage
        if (verifyLink(e.target.value)) {
          getPlaylist(e.target.value).then(res => setCurrentAlbum(res));
          localStorage.setItem('album', parseID(e.target.value));
        }
      }

    return (
        <>
        <Head>
            <title>Spotify API Project</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
            <section className={styles.card}>
            <span className={styles.description}>
                Enter spotify playlist ID or link to get started:
            </span>
            <input 
                type='text'
                className={styles.input}
                onChange={(e) => handleChangeLinks(e)} 
            />
            <Image 
                className={styles.logo}
                src={currentAlbum && currentAlbum.hasOwnProperty('images')? currentAlbum.images[0].url: defaultArt}
                width={250}
                height={250}
                alt='album image'
            >

            </Image>

            <span className={styles.description}>Current album: {currentAlbum ? currentAlbum.name : ''}</span>

            <Redirect disabled={currentAlbum ? false : true} text='Rank random' page='/random' />
            <Redirect disabled={currentAlbum ? false : true} text='Rank comprehensive' page='' />
            
            </section>
        </main>
        </>
  )
}


// TODO: fix Redirect disable code
function Redirect({text, page, disabled}) {
  return (
    <Link href={page} className={styles.button}>
      <button className={styles.button} disabled={disabled}> {text} </button>
    </Link>
  )
}
