import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [link, setLink] = useState('no album selected');

  function handleChangeLinks(e) {
    setLink(e.target.value);
  }


  return (
    <>
      <Head>
        <title>Spotify API Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <section className={styles.card}>
          <span className={styles.description}>
            Enter spotify playlist ID or link to get started:
          </span>
          <input 
            type='text'
            className={styles.input}
            onChange={(e) => handleChangeLinks(e)} 
          />
          <Image 
            className={styles.logo}
            src={'https://developer.spotify.com/images/guidelines/design/icon2@2x.png'}
            width={250}
            height={250}>
          </Image>

          <span className={styles.description}>Current album: {link}</span>

          <button disabled className={styles.button}>go</button>
          <button disabled className={styles.button}>tes</button>
          
        </section>
      </main>
    </>
  )
}
